import RequireAuth from './components/RequireAuth';
import './global.css';

export const metadata = {
  title: 'TNLCM frontend',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <RequireAuth>
      <html lang="en">
        <body>{children}</body>
      </html>
    </RequireAuth>
  )
}